<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BarbershopReservationsUni.Data.Models\BarbershopReservationsUni.Data.Models.csproj" />
    <ProjectReference Include="..\BarbershopReservationsUni.Data\BarbershopReservationsUni.Data.csproj" />
    <ProjectReference Include="..\BarbershopReservationsUni.Services\BarbershopReservationsUni.Services.csproj" />
    <ProjectReference Include="..\BarbershopReservationsUni.Web.ViewModels\BarbershopReservationsUni.Web.ViewModels.csproj" />
  </ItemGroup>

</Project>
